# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'nuevaReserva.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)
import resources_rc
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.contenedor_principal = QWidget(self.centralwidget)
        self.contenedor_principal.setObjectName(u"contenedor_principal")
        self.contenedor_principal.setGeometry(QRect(10, 10, 761, 571))
        self.contenedor_principal.setStyleSheet(u"background-color: \n"
"gray;\n"
"\n"
"")
        self.label_2 = QLabel(self.contenedor_principal)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 130, 151, 16))
        self.input_descripcion_evento = QLineEdit(self.contenedor_principal)
        self.input_descripcion_evento.setObjectName(u"input_descripcion_evento")
        self.input_descripcion_evento.setGeometry(QRect(40, 70, 113, 22))
        self.input_descripcion_evento.setStyleSheet(u"QLineEdit{\n"
"	background: white;\n"
"}")
        self.input_descripcion_evento.setReadOnly(False)
        self.label = QLabel(self.contenedor_principal)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 40, 151, 16))
        self.no_duracion_checkbox = QCheckBox(self.contenedor_principal)
        self.no_duracion_checkbox.setObjectName(u"no_duracion_checkbox")
        self.no_duracion_checkbox.setGeometry(QRect(30, 220, 101, 20))
        self.si_duracion_checkbox = QCheckBox(self.contenedor_principal)
        self.si_duracion_checkbox.setObjectName(u"si_duracion_checkbox")
        self.si_duracion_checkbox.setGeometry(QRect(150, 220, 101, 20))
        self.si_duracion_checkbox.setCheckable(True)
        self.select_dia_inicio = QComboBox(self.contenedor_principal)
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.addItem("")
        self.select_dia_inicio.setObjectName(u"select_dia_inicio")
        self.select_dia_inicio.setGeometry(QRect(30, 160, 73, 22))
        self.select_dia_inicio.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.select_dia_inicio.setEditable(True)
        self.label_3 = QLabel(self.contenedor_principal)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 310, 151, 16))
        self.select_mes_inicio = QComboBox(self.contenedor_principal)
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.addItem("")
        self.select_mes_inicio.setObjectName(u"select_mes_inicio")
        self.select_mes_inicio.setGeometry(QRect(130, 160, 121, 22))
        self.select_mes_inicio.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.select_hora_inicio = QComboBox(self.contenedor_principal)
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.addItem("")
        self.select_hora_inicio.setObjectName(u"select_hora_inicio")
        self.select_hora_inicio.setGeometry(QRect(500, 150, 73, 22))
        self.select_hora_inicio.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.select_minutos_inicio = QComboBox(self.contenedor_principal)
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.addItem("")
        self.select_minutos_inicio.setObjectName(u"select_minutos_inicio")
        self.select_minutos_inicio.setGeometry(QRect(610, 150, 73, 22))
        self.select_minutos_inicio.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.input_ano_inicio = QLineEdit(self.contenedor_principal)
        self.input_ano_inicio.setObjectName(u"input_ano_inicio")
        self.input_ano_inicio.setGeometry(QRect(280, 160, 113, 22))
        self.input_ano_inicio.setStyleSheet(u"QLineEdit{\n"
"	background: white;\n"
"}")
        self.input_ano_inicio.setReadOnly(False)
        self.select_mes_final = QComboBox(self.contenedor_principal)
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.addItem("")
        self.select_mes_final.setObjectName(u"select_mes_final")
        self.select_mes_final.setGeometry(QRect(102, 390, 111, 22))
        self.select_mes_final.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.select_hora_final = QComboBox(self.contenedor_principal)
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.addItem("")
        self.select_hora_final.setObjectName(u"select_hora_final")
        self.select_hora_final.setGeometry(QRect(350, 390, 73, 22))
        self.select_hora_final.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.input_ano_final = QLineEdit(self.contenedor_principal)
        self.input_ano_final.setObjectName(u"input_ano_final")
        self.input_ano_final.setGeometry(QRect(220, 390, 113, 22))
        self.input_ano_final.setStyleSheet(u"QLineEdit{\n"
"	background: white;\n"
"}")
        self.input_ano_final.setReadOnly(False)
        self.select_minuto_final = QComboBox(self.contenedor_principal)
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.addItem("")
        self.select_minuto_final.setObjectName(u"select_minuto_final")
        self.select_minuto_final.setGeometry(QRect(620, 420, 73, 22))
        self.select_minuto_final.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.select_dia_final = QComboBox(self.contenedor_principal)
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.addItem("")
        self.select_dia_final.setObjectName(u"select_dia_final")
        self.select_dia_final.setGeometry(QRect(20, 390, 73, 22))
        self.select_dia_final.setStyleSheet(u"QComboBox{\n"
"	background: white;\n"
"}")
        self.pushButton = QPushButton(self.contenedor_principal)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(420, 500, 141, 28))
        self.pushButton.setStyleSheet(u"QPushButton{\n"
"	background: blue;\n"
"}")
        self.comboBox = QComboBox(self.contenedor_principal)
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(580, 310, 73, 22))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"fecha", None))
        self.input_descripcion_evento.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"descripci\u00f3n del evento", None))
        self.no_duracion_checkbox.setText(QCoreApplication.translate("MainWindow", u"sin duraci\u00f3n", None))
        self.si_duracion_checkbox.setText(QCoreApplication.translate("MainWindow", u"con duraci\u00f3n", None))
        self.select_dia_inicio.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_dia_inicio.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_dia_inicio.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_dia_inicio.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_dia_inicio.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_dia_inicio.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.select_dia_inicio.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.select_dia_inicio.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.select_dia_inicio.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.select_dia_inicio.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))
        self.select_dia_inicio.setItemText(10, QCoreApplication.translate("MainWindow", u"11", None))
        self.select_dia_inicio.setItemText(11, QCoreApplication.translate("MainWindow", u"12", None))
        self.select_dia_inicio.setItemText(12, QCoreApplication.translate("MainWindow", u"13", None))
        self.select_dia_inicio.setItemText(13, QCoreApplication.translate("MainWindow", u"14", None))
        self.select_dia_inicio.setItemText(14, QCoreApplication.translate("MainWindow", u"15", None))
        self.select_dia_inicio.setItemText(15, QCoreApplication.translate("MainWindow", u"16", None))
        self.select_dia_inicio.setItemText(16, QCoreApplication.translate("MainWindow", u"17", None))
        self.select_dia_inicio.setItemText(17, QCoreApplication.translate("MainWindow", u"18", None))
        self.select_dia_inicio.setItemText(18, QCoreApplication.translate("MainWindow", u"19", None))
        self.select_dia_inicio.setItemText(19, QCoreApplication.translate("MainWindow", u"20", None))
        self.select_dia_inicio.setItemText(20, QCoreApplication.translate("MainWindow", u"21", None))
        self.select_dia_inicio.setItemText(21, QCoreApplication.translate("MainWindow", u"22", None))
        self.select_dia_inicio.setItemText(22, QCoreApplication.translate("MainWindow", u"23", None))
        self.select_dia_inicio.setItemText(23, QCoreApplication.translate("MainWindow", u"24", None))
        self.select_dia_inicio.setItemText(24, QCoreApplication.translate("MainWindow", u"25", None))
        self.select_dia_inicio.setItemText(25, QCoreApplication.translate("MainWindow", u"26", None))
        self.select_dia_inicio.setItemText(26, QCoreApplication.translate("MainWindow", u"27", None))
        self.select_dia_inicio.setItemText(27, QCoreApplication.translate("MainWindow", u"28", None))
        self.select_dia_inicio.setItemText(28, QCoreApplication.translate("MainWindow", u"29", None))
        self.select_dia_inicio.setItemText(29, QCoreApplication.translate("MainWindow", u"30", None))
        self.select_dia_inicio.setItemText(30, QCoreApplication.translate("MainWindow", u"31", None))

        self.label_3.setText("")
        self.select_mes_inicio.setItemText(0, QCoreApplication.translate("MainWindow", u"Enero", None))
        self.select_mes_inicio.setItemText(1, QCoreApplication.translate("MainWindow", u"Febrero", None))
        self.select_mes_inicio.setItemText(2, QCoreApplication.translate("MainWindow", u"Marzo", None))
        self.select_mes_inicio.setItemText(3, QCoreApplication.translate("MainWindow", u"Abril", None))
        self.select_mes_inicio.setItemText(4, QCoreApplication.translate("MainWindow", u"Mayo", None))
        self.select_mes_inicio.setItemText(5, QCoreApplication.translate("MainWindow", u"Junio", None))
        self.select_mes_inicio.setItemText(6, QCoreApplication.translate("MainWindow", u"Julio", None))
        self.select_mes_inicio.setItemText(7, QCoreApplication.translate("MainWindow", u"Agosto", None))
        self.select_mes_inicio.setItemText(8, QCoreApplication.translate("MainWindow", u"Septiembre", None))
        self.select_mes_inicio.setItemText(9, QCoreApplication.translate("MainWindow", u"Octubre", None))
        self.select_mes_inicio.setItemText(10, QCoreApplication.translate("MainWindow", u"Noviembre", None))
        self.select_mes_inicio.setItemText(11, QCoreApplication.translate("MainWindow", u"Diciembre", None))

        self.select_hora_inicio.setItemText(0, QCoreApplication.translate("MainWindow", u"6", None))
        self.select_hora_inicio.setItemText(1, QCoreApplication.translate("MainWindow", u"7", None))
        self.select_hora_inicio.setItemText(2, QCoreApplication.translate("MainWindow", u"8", None))
        self.select_hora_inicio.setItemText(3, QCoreApplication.translate("MainWindow", u"9", None))
        self.select_hora_inicio.setItemText(4, QCoreApplication.translate("MainWindow", u"10", None))
        self.select_hora_inicio.setItemText(5, QCoreApplication.translate("MainWindow", u"11", None))
        self.select_hora_inicio.setItemText(6, QCoreApplication.translate("MainWindow", u"12", None))
        self.select_hora_inicio.setItemText(7, QCoreApplication.translate("MainWindow", u"13", None))
        self.select_hora_inicio.setItemText(8, QCoreApplication.translate("MainWindow", u"14", None))
        self.select_hora_inicio.setItemText(9, QCoreApplication.translate("MainWindow", u"15", None))
        self.select_hora_inicio.setItemText(10, QCoreApplication.translate("MainWindow", u"16", None))
        self.select_hora_inicio.setItemText(11, QCoreApplication.translate("MainWindow", u"17", None))
        self.select_hora_inicio.setItemText(12, QCoreApplication.translate("MainWindow", u"18", None))
        self.select_hora_inicio.setItemText(13, QCoreApplication.translate("MainWindow", u"19", None))
        self.select_hora_inicio.setItemText(14, QCoreApplication.translate("MainWindow", u"20", None))
        self.select_hora_inicio.setItemText(15, QCoreApplication.translate("MainWindow", u"21", None))
        self.select_hora_inicio.setItemText(16, QCoreApplication.translate("MainWindow", u"22", None))

        self.select_minutos_inicio.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_minutos_inicio.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_minutos_inicio.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_minutos_inicio.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_minutos_inicio.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_minutos_inicio.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.select_minutos_inicio.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.select_minutos_inicio.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.select_minutos_inicio.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.select_minutos_inicio.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))
        self.select_minutos_inicio.setItemText(10, QCoreApplication.translate("MainWindow", u"11", None))
        self.select_minutos_inicio.setItemText(11, QCoreApplication.translate("MainWindow", u"12", None))
        self.select_minutos_inicio.setItemText(12, QCoreApplication.translate("MainWindow", u"13", None))
        self.select_minutos_inicio.setItemText(13, QCoreApplication.translate("MainWindow", u"14", None))
        self.select_minutos_inicio.setItemText(14, QCoreApplication.translate("MainWindow", u"15", None))
        self.select_minutos_inicio.setItemText(15, QCoreApplication.translate("MainWindow", u"16", None))
        self.select_minutos_inicio.setItemText(16, QCoreApplication.translate("MainWindow", u"17", None))
        self.select_minutos_inicio.setItemText(17, QCoreApplication.translate("MainWindow", u"18", None))
        self.select_minutos_inicio.setItemText(18, QCoreApplication.translate("MainWindow", u"19", None))
        self.select_minutos_inicio.setItemText(19, QCoreApplication.translate("MainWindow", u"20", None))
        self.select_minutos_inicio.setItemText(20, QCoreApplication.translate("MainWindow", u"21", None))
        self.select_minutos_inicio.setItemText(21, QCoreApplication.translate("MainWindow", u"22", None))
        self.select_minutos_inicio.setItemText(22, QCoreApplication.translate("MainWindow", u"23", None))
        self.select_minutos_inicio.setItemText(23, QCoreApplication.translate("MainWindow", u"24", None))
        self.select_minutos_inicio.setItemText(24, QCoreApplication.translate("MainWindow", u"25", None))
        self.select_minutos_inicio.setItemText(25, QCoreApplication.translate("MainWindow", u"26", None))
        self.select_minutos_inicio.setItemText(26, QCoreApplication.translate("MainWindow", u"27", None))
        self.select_minutos_inicio.setItemText(27, QCoreApplication.translate("MainWindow", u"28", None))
        self.select_minutos_inicio.setItemText(28, QCoreApplication.translate("MainWindow", u"29", None))
        self.select_minutos_inicio.setItemText(29, QCoreApplication.translate("MainWindow", u"30", None))
        self.select_minutos_inicio.setItemText(30, QCoreApplication.translate("MainWindow", u"31", None))
        self.select_minutos_inicio.setItemText(31, QCoreApplication.translate("MainWindow", u"32", None))
        self.select_minutos_inicio.setItemText(32, QCoreApplication.translate("MainWindow", u"33", None))
        self.select_minutos_inicio.setItemText(33, QCoreApplication.translate("MainWindow", u"34", None))
        self.select_minutos_inicio.setItemText(34, QCoreApplication.translate("MainWindow", u"35", None))
        self.select_minutos_inicio.setItemText(35, QCoreApplication.translate("MainWindow", u"36", None))
        self.select_minutos_inicio.setItemText(36, QCoreApplication.translate("MainWindow", u"37", None))
        self.select_minutos_inicio.setItemText(37, QCoreApplication.translate("MainWindow", u"38", None))
        self.select_minutos_inicio.setItemText(38, QCoreApplication.translate("MainWindow", u"39", None))
        self.select_minutos_inicio.setItemText(39, QCoreApplication.translate("MainWindow", u"40", None))
        self.select_minutos_inicio.setItemText(40, QCoreApplication.translate("MainWindow", u"41", None))
        self.select_minutos_inicio.setItemText(41, QCoreApplication.translate("MainWindow", u"42", None))
        self.select_minutos_inicio.setItemText(42, QCoreApplication.translate("MainWindow", u"43", None))
        self.select_minutos_inicio.setItemText(43, QCoreApplication.translate("MainWindow", u"44", None))
        self.select_minutos_inicio.setItemText(44, QCoreApplication.translate("MainWindow", u"45", None))
        self.select_minutos_inicio.setItemText(45, QCoreApplication.translate("MainWindow", u"46", None))
        self.select_minutos_inicio.setItemText(46, QCoreApplication.translate("MainWindow", u"47", None))
        self.select_minutos_inicio.setItemText(47, QCoreApplication.translate("MainWindow", u"48", None))
        self.select_minutos_inicio.setItemText(48, QCoreApplication.translate("MainWindow", u"49", None))
        self.select_minutos_inicio.setItemText(49, QCoreApplication.translate("MainWindow", u"50", None))
        self.select_minutos_inicio.setItemText(50, QCoreApplication.translate("MainWindow", u"51", None))
        self.select_minutos_inicio.setItemText(51, QCoreApplication.translate("MainWindow", u"52", None))
        self.select_minutos_inicio.setItemText(52, QCoreApplication.translate("MainWindow", u"53", None))
        self.select_minutos_inicio.setItemText(53, QCoreApplication.translate("MainWindow", u"54", None))
        self.select_minutos_inicio.setItemText(54, QCoreApplication.translate("MainWindow", u"55", None))
        self.select_minutos_inicio.setItemText(55, QCoreApplication.translate("MainWindow", u"56", None))
        self.select_minutos_inicio.setItemText(56, QCoreApplication.translate("MainWindow", u"57", None))
        self.select_minutos_inicio.setItemText(57, QCoreApplication.translate("MainWindow", u"58", None))
        self.select_minutos_inicio.setItemText(58, QCoreApplication.translate("MainWindow", u"59", None))

        self.input_ano_inicio.setText(QCoreApplication.translate("MainWindow", u"2020", None))
        self.select_mes_final.setItemText(0, QCoreApplication.translate("MainWindow", u"Enero", None))
        self.select_mes_final.setItemText(1, QCoreApplication.translate("MainWindow", u"Febrero", None))
        self.select_mes_final.setItemText(2, QCoreApplication.translate("MainWindow", u"Marzo", None))
        self.select_mes_final.setItemText(3, QCoreApplication.translate("MainWindow", u"Abril", None))
        self.select_mes_final.setItemText(4, QCoreApplication.translate("MainWindow", u"Mayo", None))
        self.select_mes_final.setItemText(5, QCoreApplication.translate("MainWindow", u"Junio", None))
        self.select_mes_final.setItemText(6, QCoreApplication.translate("MainWindow", u"Julio", None))
        self.select_mes_final.setItemText(7, QCoreApplication.translate("MainWindow", u"Agosto", None))
        self.select_mes_final.setItemText(8, QCoreApplication.translate("MainWindow", u"Septiembre", None))
        self.select_mes_final.setItemText(9, QCoreApplication.translate("MainWindow", u"Octubre", None))
        self.select_mes_final.setItemText(10, QCoreApplication.translate("MainWindow", u"Noviembre", None))
        self.select_mes_final.setItemText(11, QCoreApplication.translate("MainWindow", u"Diciembre", None))

        self.select_hora_final.setItemText(0, QCoreApplication.translate("MainWindow", u"6", None))
        self.select_hora_final.setItemText(1, QCoreApplication.translate("MainWindow", u"7", None))
        self.select_hora_final.setItemText(2, QCoreApplication.translate("MainWindow", u"8", None))
        self.select_hora_final.setItemText(3, QCoreApplication.translate("MainWindow", u"9", None))
        self.select_hora_final.setItemText(4, QCoreApplication.translate("MainWindow", u"10", None))
        self.select_hora_final.setItemText(5, QCoreApplication.translate("MainWindow", u"11", None))
        self.select_hora_final.setItemText(6, QCoreApplication.translate("MainWindow", u"12", None))
        self.select_hora_final.setItemText(7, QCoreApplication.translate("MainWindow", u"13", None))
        self.select_hora_final.setItemText(8, QCoreApplication.translate("MainWindow", u"14", None))
        self.select_hora_final.setItemText(9, QCoreApplication.translate("MainWindow", u"15", None))
        self.select_hora_final.setItemText(10, QCoreApplication.translate("MainWindow", u"16", None))
        self.select_hora_final.setItemText(11, QCoreApplication.translate("MainWindow", u"17", None))
        self.select_hora_final.setItemText(12, QCoreApplication.translate("MainWindow", u"18", None))
        self.select_hora_final.setItemText(13, QCoreApplication.translate("MainWindow", u"19", None))
        self.select_hora_final.setItemText(14, QCoreApplication.translate("MainWindow", u"20", None))
        self.select_hora_final.setItemText(15, QCoreApplication.translate("MainWindow", u"21", None))
        self.select_hora_final.setItemText(16, QCoreApplication.translate("MainWindow", u"22", None))

        self.input_ano_final.setText(QCoreApplication.translate("MainWindow", u"2020", None))
        self.select_minuto_final.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_minuto_final.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_minuto_final.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_minuto_final.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_minuto_final.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_minuto_final.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.select_minuto_final.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.select_minuto_final.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.select_minuto_final.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.select_minuto_final.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))
        self.select_minuto_final.setItemText(10, QCoreApplication.translate("MainWindow", u"11", None))
        self.select_minuto_final.setItemText(11, QCoreApplication.translate("MainWindow", u"12", None))
        self.select_minuto_final.setItemText(12, QCoreApplication.translate("MainWindow", u"13", None))
        self.select_minuto_final.setItemText(13, QCoreApplication.translate("MainWindow", u"14", None))
        self.select_minuto_final.setItemText(14, QCoreApplication.translate("MainWindow", u"15", None))
        self.select_minuto_final.setItemText(15, QCoreApplication.translate("MainWindow", u"16", None))
        self.select_minuto_final.setItemText(16, QCoreApplication.translate("MainWindow", u"17", None))
        self.select_minuto_final.setItemText(17, QCoreApplication.translate("MainWindow", u"18", None))
        self.select_minuto_final.setItemText(18, QCoreApplication.translate("MainWindow", u"19", None))
        self.select_minuto_final.setItemText(19, QCoreApplication.translate("MainWindow", u"20", None))
        self.select_minuto_final.setItemText(20, QCoreApplication.translate("MainWindow", u"21", None))
        self.select_minuto_final.setItemText(21, QCoreApplication.translate("MainWindow", u"22", None))
        self.select_minuto_final.setItemText(22, QCoreApplication.translate("MainWindow", u"23", None))
        self.select_minuto_final.setItemText(23, QCoreApplication.translate("MainWindow", u"24", None))
        self.select_minuto_final.setItemText(24, QCoreApplication.translate("MainWindow", u"25", None))
        self.select_minuto_final.setItemText(25, QCoreApplication.translate("MainWindow", u"26", None))
        self.select_minuto_final.setItemText(26, QCoreApplication.translate("MainWindow", u"27", None))
        self.select_minuto_final.setItemText(27, QCoreApplication.translate("MainWindow", u"28", None))
        self.select_minuto_final.setItemText(28, QCoreApplication.translate("MainWindow", u"29", None))
        self.select_minuto_final.setItemText(29, QCoreApplication.translate("MainWindow", u"30", None))
        self.select_minuto_final.setItemText(30, QCoreApplication.translate("MainWindow", u"31", None))
        self.select_minuto_final.setItemText(31, QCoreApplication.translate("MainWindow", u"32", None))
        self.select_minuto_final.setItemText(32, QCoreApplication.translate("MainWindow", u"33", None))
        self.select_minuto_final.setItemText(33, QCoreApplication.translate("MainWindow", u"34", None))
        self.select_minuto_final.setItemText(34, QCoreApplication.translate("MainWindow", u"35", None))
        self.select_minuto_final.setItemText(35, QCoreApplication.translate("MainWindow", u"36", None))
        self.select_minuto_final.setItemText(36, QCoreApplication.translate("MainWindow", u"37", None))
        self.select_minuto_final.setItemText(37, QCoreApplication.translate("MainWindow", u"38", None))
        self.select_minuto_final.setItemText(38, QCoreApplication.translate("MainWindow", u"39", None))
        self.select_minuto_final.setItemText(39, QCoreApplication.translate("MainWindow", u"40", None))
        self.select_minuto_final.setItemText(40, QCoreApplication.translate("MainWindow", u"41", None))
        self.select_minuto_final.setItemText(41, QCoreApplication.translate("MainWindow", u"42", None))
        self.select_minuto_final.setItemText(42, QCoreApplication.translate("MainWindow", u"43", None))
        self.select_minuto_final.setItemText(43, QCoreApplication.translate("MainWindow", u"44", None))
        self.select_minuto_final.setItemText(44, QCoreApplication.translate("MainWindow", u"45", None))
        self.select_minuto_final.setItemText(45, QCoreApplication.translate("MainWindow", u"46", None))
        self.select_minuto_final.setItemText(46, QCoreApplication.translate("MainWindow", u"47", None))
        self.select_minuto_final.setItemText(47, QCoreApplication.translate("MainWindow", u"48", None))
        self.select_minuto_final.setItemText(48, QCoreApplication.translate("MainWindow", u"49", None))
        self.select_minuto_final.setItemText(49, QCoreApplication.translate("MainWindow", u"50", None))
        self.select_minuto_final.setItemText(50, QCoreApplication.translate("MainWindow", u"51", None))
        self.select_minuto_final.setItemText(51, QCoreApplication.translate("MainWindow", u"52", None))
        self.select_minuto_final.setItemText(52, QCoreApplication.translate("MainWindow", u"53", None))
        self.select_minuto_final.setItemText(53, QCoreApplication.translate("MainWindow", u"54", None))
        self.select_minuto_final.setItemText(54, QCoreApplication.translate("MainWindow", u"55", None))
        self.select_minuto_final.setItemText(55, QCoreApplication.translate("MainWindow", u"56", None))
        self.select_minuto_final.setItemText(56, QCoreApplication.translate("MainWindow", u"57", None))
        self.select_minuto_final.setItemText(57, QCoreApplication.translate("MainWindow", u"58", None))
        self.select_minuto_final.setItemText(58, QCoreApplication.translate("MainWindow", u"59", None))

        self.select_dia_final.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_dia_final.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_dia_final.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_dia_final.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_dia_final.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_dia_final.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.select_dia_final.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.select_dia_final.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.select_dia_final.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.select_dia_final.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))
        self.select_dia_final.setItemText(10, QCoreApplication.translate("MainWindow", u"11", None))
        self.select_dia_final.setItemText(11, QCoreApplication.translate("MainWindow", u"12", None))
        self.select_dia_final.setItemText(12, QCoreApplication.translate("MainWindow", u"13", None))
        self.select_dia_final.setItemText(13, QCoreApplication.translate("MainWindow", u"14", None))
        self.select_dia_final.setItemText(14, QCoreApplication.translate("MainWindow", u"15", None))
        self.select_dia_final.setItemText(15, QCoreApplication.translate("MainWindow", u"16", None))
        self.select_dia_final.setItemText(16, QCoreApplication.translate("MainWindow", u"17", None))
        self.select_dia_final.setItemText(17, QCoreApplication.translate("MainWindow", u"18", None))
        self.select_dia_final.setItemText(18, QCoreApplication.translate("MainWindow", u"19", None))
        self.select_dia_final.setItemText(19, QCoreApplication.translate("MainWindow", u"20", None))
        self.select_dia_final.setItemText(20, QCoreApplication.translate("MainWindow", u"21", None))
        self.select_dia_final.setItemText(21, QCoreApplication.translate("MainWindow", u"22", None))
        self.select_dia_final.setItemText(22, QCoreApplication.translate("MainWindow", u"23", None))
        self.select_dia_final.setItemText(23, QCoreApplication.translate("MainWindow", u"24", None))
        self.select_dia_final.setItemText(24, QCoreApplication.translate("MainWindow", u"25", None))
        self.select_dia_final.setItemText(25, QCoreApplication.translate("MainWindow", u"26", None))
        self.select_dia_final.setItemText(26, QCoreApplication.translate("MainWindow", u"27", None))
        self.select_dia_final.setItemText(27, QCoreApplication.translate("MainWindow", u"28", None))
        self.select_dia_final.setItemText(28, QCoreApplication.translate("MainWindow", u"29", None))
        self.select_dia_final.setItemText(29, QCoreApplication.translate("MainWindow", u"30", None))
        self.select_dia_final.setItemText(30, QCoreApplication.translate("MainWindow", u"31", None))

        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"CREAR RESERVA", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"SALON", None))

    # retranslateUi

